version: "3.8"

services:
  app:
    build: .
    container_name: sis_app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: sis_db
    environment:
      POSTGRES_DB: sis_db
      POSTGRES_USER: sis_user
      POSTGRES_PASSWORD: sis_pass
    ports:
      - "5432:5432"
