version: "3.8"

services:
  db:
    image: postgres:15
    container_name: sis_db
    restart: always
    environment:
      POSTGRES_DB: sis_db
      POSTGRES_USER: sis_user
      POSTGRES_PASSWORD: sis_pass
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pg_data:

