version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: sis_db
    environment:
      POSTGRES_DB: sis_db
      POSTGRES_USER: sis_user
      POSTGRES_PASSWORD: sis_pass
    ports:
      - "5432:5432"
